
spring:
  application:
    name: rpc-consumer
server:
  port: 8002
swagger:
  enable: true
netty:
  server:
    port: 11211
logging:
  level: info

wlb:
  rpc:
    enable: true
    common:
      encode: HESSIAN

    client:
      servicename: consumer
      aways-retry: true
      aways-retry-interval: 60
      init-retry-time: 5

    server:
      ip: 127.0.0.1
      port: 11211