spring:
  application:
    name: rpc-server

# web port
server:
  port: 8000

# 是否打开swagger
swagger:
  enable: true

wlb:
  rpc:
    server:
      port: 11211
      execute:
        enable: true
        factory: CUSTOM
        cache: JDK
        balance-arithmetic: ROUND
      balance:
        enable: true


logging:
  level:
    root: info

